apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: VAR1
      valueFrom: 
        configMapKeyRef:
          name: cmenv
          key: var1
    - name: VAR2
      valueFrom:
        configMapKeyRef:
          name: cmenv
          key: var2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
