apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      typ: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        typ: app
    spec:
      containers:
      - image: nginx:1.17.1
        name: nginx
        ports:
          - containerPort: 80
        resources: {}
status: {}
