apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
      - name: liveness-port
        containerPort: 8080
        hostPort: 8080
    resources: {}
    livenessProbe:
      httpGet:
        path: /healthz
        port: liveness-port
      failureThreshold: 1
      periodSeconds: 10    
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
