apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: hello
spec:
  completions: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - echo
        - Hello
        - babe
        image: busybox
        name: hello
        resources: {}
      restartPolicy: Never
status: {}
