apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: busybox
spec:
  activeDeadlineSeconds: 30
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do echo hello; sleep 10; done
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        resources: {}
      restartPolicy: Never
status: {}
