kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
  labels:
    typ: app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
