apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes: 
  - name: myvol
    persistentVolumeClaim:
      claimName: mypvc
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: myvol
      mountPath: "/usr/share/nginx/html"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
