apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: myvol
    emptyDir: {}
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo 'Hi I am from Main container' >> /var/log/index.html; sleep 5; done
    image: nginx
    name: nginx
    resources: {}
    volumeMounts: 
    - name: myvol
      mountPath: /var/log
  - image: nginx 
    name: sidecar-container
    resources: {}
    ports:
      - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
