apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
  - name: myvol
    emptyDir: {}
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo 'Hello kese hu yar <3' >> /var/log/index.html; sleep 5;
      done
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
    - name: myvol
      mountPath: /var/log
  - image: nginx
    name: sidecar-container
    ports:
      - containerPort: 80
    resources: {}
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
