apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxx
  name: nginxx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginxx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
