kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access
spec:
  podSelector:
    matchLabels:
      run: nginx 
  ingress:
  - from: 
    - podSelector:
        matchLabels:
          access: granted
