kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv
  labels:
    typ: app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
