kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv 
  labels:
    typ: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
