apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  volumes:
  - name: myvol
    emptyDir: {}
  containers:
  - image: redis
    name: redis
    volumeMounts:
    - name: myvol
      mountPath: /redis/data
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
