apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busbox
  name: busbox
spec:
  securityContext:
    runAsUser: 101
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
