apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyboxx
  name: busyboxx
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    securityContext:
      runAsUser: 2000
    name: busyboxx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
