apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: myvol
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default
